project:
  type: book
  output-dir: docs

book:
  title: "Con-Gen-2022"
  author: "Eric C. Anderson"
  date: "8/27/2022"
  chapters:
    - index.qmd
    - probinf.qmd
    - snakemake.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

